#!/bin/sh
set -eu

if [ "$#" != 1 ]; then
    echo "Usage: hxconvert <rootfs>"
    exit 1
fi

HxRoot="$(realpath "$1")"

find "$1" -type l | while read l; do
    c="$(readlink "$l")"
    case "$c" in
        /*) ;;
        *) continue;;
    esac
    rc="$HxRoot$c"
    rm "$l"
    ln -sv "$rc" "$l"
done

ln -sfv /proc/mounts "$1"/etc/mtab

echo Done
